apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bandjoun-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wilses10/app-ressencer.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: bandjoun

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true