apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: bandjoun
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "bandjoun2024"
  MYSQL_USER: "recensement_user"
  MYSQL_PASSWORD: "bandjoun2024"
  MYSQL_DATABASE: "recensement_bandjoun"
  MYSQL_HOST: "bandjoun-mysql.cqxkqw8qs7o3.us-east-1.rds.amazonaws.com"
