apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: bandjoun
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "placeholder"
  MYSQL_USER: "recensement_user"
  MYSQL_PASSWORD: "placeholder"
  MYSQL_DATABASE: "recensement_bandjoun"
